name: gru
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - pytorch=1.4.0
  - torchvision
  - cudatoolkit
  - visdom
  - joblib
  - tqdm
  - matplotlib
  - opencv
  - pypng

